-- ============================================================================
-- HAPPY SURGICALS - ADMIN FIX SCRIPT (V2)
-- ============================================================================
-- This script fixes missing schema columns, CREATES missing tables, 
-- and applies proper RLS policies for: sampalraj2001@gmail.com
--
-- INSTRUCTIONS:
-- 1. Go to Supabase Dashboard > SQL Editor.
-- 2. Paste this entire script and click "Run".
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. SCHEMA VERIFICATION & UPDATES
-- ----------------------------------------------------------------------------

-- A. Update 'products' table
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS short_description TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS code TEXT;  -- SKU
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS img TEXT;   -- Main Image URL
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS inherit_certificates BOOLEAN DEFAULT true;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS specifications JSONB DEFAULT '[]'::jsonb; 

-- B. Ensure 'product_variants' exists
CREATE TABLE IF NOT EXISTS public.product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    size TEXT,
    color TEXT,
    material TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- C. Ensure 'product_certificates' junction table exists
CREATE TABLE IF NOT EXISTS public.product_certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    certificate_id BIGINT REFERENCES public.certificates(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(product_id, certificate_id)
);

-- D. Ensure 'audit_logs' exists (MISSING TABLE FIX)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_email TEXT,
    action TEXT,
    target TEXT,
    details TEXT
);

-- ----------------------------------------------------------------------------
-- 2. ROW LEVEL SECURITY (RLS) POLICIES
-- ----------------------------------------------------------------------------

-- Enable RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- 1. PRODUCTS
DROP POLICY IF EXISTS "Admin Full Access Products" ON public.products;
CREATE POLICY "Admin Full Access Products" ON public.products
FOR ALL USING (auth.email() = 'sampalraj2001@gmail.com') WITH CHECK (auth.email() = 'sampalraj2001@gmail.com');

-- 2. CATEGORIES
DROP POLICY IF EXISTS "Admin Full Access Categories" ON public.categories;
CREATE POLICY "Admin Full Access Categories" ON public.categories
FOR ALL USING (auth.email() = 'sampalraj2001@gmail.com') WITH CHECK (auth.email() = 'sampalraj2001@gmail.com');

-- 3. SEGMENTS
DROP POLICY IF EXISTS "Admin Full Access Segments" ON public.segments;
CREATE POLICY "Admin Full Access Segments" ON public.segments
FOR ALL USING (auth.email() = 'sampalraj2001@gmail.com') WITH CHECK (auth.email() = 'sampalraj2001@gmail.com');

-- 4. CERTIFICATES
DROP POLICY IF EXISTS "Admin Full Access Certificates" ON public.certificates;
CREATE POLICY "Admin Full Access Certificates" ON public.certificates
FOR ALL USING (auth.email() = 'sampalraj2001@gmail.com') WITH CHECK (auth.email() = 'sampalraj2001@gmail.com');

-- 5. VARIANTS
DROP POLICY IF EXISTS "Admin Full Access Variants" ON public.product_variants;
CREATE POLICY "Admin Full Access Variants" ON public.product_variants
FOR ALL USING (auth.email() = 'sampalraj2001@gmail.com') WITH CHECK (auth.email() = 'sampalraj2001@gmail.com');

-- 6. PRODUCT CERTIFICATES (Junction)
DROP POLICY IF EXISTS "Admin Full Access ProdCerts" ON public.product_certificates;
CREATE POLICY "Admin Full Access ProdCerts" ON public.product_certificates
FOR ALL USING (auth.email() = 'sampalraj2001@gmail.com') WITH CHECK (auth.email() = 'sampalraj2001@gmail.com');

-- 7. AUDIT LOGS
DROP POLICY IF EXISTS "Admin Full Access Logs" ON public.audit_logs;
CREATE POLICY "Admin Full Access Logs" ON public.audit_logs
FOR ALL USING (auth.email() = 'sampalraj2001@gmail.com') WITH CHECK (auth.email() = 'sampalraj2001@gmail.com');

-- Public Read Access
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Products') THEN
        CREATE POLICY "Public Read Products" ON public.products FOR SELECT TO anon, authenticated USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Categories') THEN
        CREATE POLICY "Public Read Categories" ON public.categories FOR SELECT TO anon, authenticated USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Segments') THEN
        CREATE POLICY "Public Read Segments" ON public.segments FOR SELECT TO anon, authenticated USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Certificates') THEN
        CREATE POLICY "Public Read Certificates" ON public.certificates FOR SELECT TO anon, authenticated USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Variants') THEN
        CREATE POLICY "Public Read Variants" ON public.product_variants FOR SELECT TO anon, authenticated USING (true);
    END IF;
END $$;


-- ----------------------------------------------------------------------------
-- 3. STORAGE POLICIES
-- ----------------------------------------------------------------------------

-- A. Product Images
DROP POLICY IF EXISTS "Admin Insert Images" ON storage.objects;
CREATE POLICY "Admin Insert Images" ON storage.objects FOR INSERT TO authenticated 
WITH CHECK (bucket_id = 'product-images' AND auth.email() = 'sampalraj2001@gmail.com');

DROP POLICY IF EXISTS "Admin Update Images" ON storage.objects;
CREATE POLICY "Admin Update Images" ON storage.objects FOR UPDATE TO authenticated 
USING (bucket_id = 'product-images' AND auth.email() = 'sampalraj2001@gmail.com');

DROP POLICY IF EXISTS "Admin Delete Images" ON storage.objects;
CREATE POLICY "Admin Delete Images" ON storage.objects FOR DELETE TO authenticated 
USING (bucket_id = 'product-images' AND auth.email() = 'sampalraj2001@gmail.com');

-- B. Certificates
DROP POLICY IF EXISTS "Admin Insert Certs" ON storage.objects;
CREATE POLICY "Admin Insert Certs" ON storage.objects FOR INSERT TO authenticated 
WITH CHECK (bucket_id = 'certificates' AND auth.email() = 'sampalraj2001@gmail.com');

DROP POLICY IF EXISTS "Admin Update Certs" ON storage.objects;
CREATE POLICY "Admin Update Certs" ON storage.objects FOR UPDATE TO authenticated 
USING (bucket_id = 'certificates' AND auth.email() = 'sampalraj2001@gmail.com');

-- Enable Public Read for images
DROP POLICY IF EXISTS "Public Read Product Images" ON storage.objects;
CREATE POLICY "Public Read Product Images" ON storage.objects FOR SELECT TO public 
USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Public Read Certificates" ON storage.objects;
CREATE POLICY "Public Read Certificates" ON storage.objects FOR SELECT TO public 
USING (bucket_id = 'certificates');
